CREATE TABLE "press" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "publisher_name" VARCHAR(255) NOT NULL,
  "publisher_profile_img_link" VARCHAR(255) NOT NULL,
  "thumbnail_s3_path" VARCHAR(255) NOT NULL,

  "description" VARCHAR(255) NOT NULL,
  "title" VARCHAR(255) NOT NULL,

  "external_url" VARCHAR(255) NOT NULL,
  "category" TEXT[] NOT NULL,
  "published_at" timestamp NOT NULL,

  "created_at" timestamp NOT NULL DEFAULT NOW()
);
