CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  "name" text NOT NULL,
  "password_hash" text NOT NULL,
  "role" TEXT[] NOT NULL,

  "created_at" timestamp NOT NULL DEFAULT NOW()
);


CREATE TABLE "blogs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_id" INTEGER NOT NULL,

  "title" VARCHAR(255) NOT NULL,
  "content" TEXT NOT NULL, 

  tsv_content tsvector, -- for indexing search

  "thumbnail_s3_path" VARCHAR(255) NOT NULL,
  "category" TEXT[] NOT NULL,

  "created_at" timestamp NOT NULL DEFAULT NOW()
);
