CREATE TABLE "press" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_id" INTEGER NOT NULL DEFAULT 0,
  "thumbnail_s3_path" VARCHAR(255) NOT NULL DEFAULT '',

  "description" VARCHAR(255) NOT NULL DEFAULT '',
  "title" VARCHAR(255) NOT NULL DEFAULT '',
  "is_deleted" BOOLEAN NOT NULL DEFAULT FALSE,
  "is_published" BOOLEAN NOT NULL DEFAULT FALSE,
  "is_featured" BOOLEAN NOT NULL DEFAULT FALSE,

  "external_url" VARCHAR(255) NOT NULL DEFAULT '',
  "category" TEXT[] DEFAULT '{}',
  "published_at" timestamp DEFAULT NOW(),

  "created_at" timestamp DEFAULT NOW()
);
