// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	PasswordHash    string           `json:"password_hash"`
	Role            []string         `json:"role"`
	ThumbnailS3Path string           `json:"thumbnail_s3_path"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Blog struct {
	ID              int32            `json:"id"`
	AuthorID        int32            `json:"author_id"`
	Description     string           `json:"description"`
	Title           string           `json:"title"`
	Content         string           `json:"content"`
	ReadTime        int32            `json:"read_time"`
	TsvContent      interface{}      `json:"tsv_content"`
	ThumbnailS3Path string           `json:"thumbnail_s3_path"`
	Category        []string         `json:"category"`
	IsFeatured      bool             `json:"is_featured"`
	IsDeleted       bool             `json:"is_deleted"`
	IsPublished     bool             `json:"is_published"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Press struct {
	ID              int32            `json:"id"`
	AuthorID        int32            `json:"author_id"`
	ThumbnailS3Path string           `json:"thumbnail_s3_path"`
	Description     string           `json:"description"`
	Title           string           `json:"title"`
	IsDeleted       bool             `json:"is_deleted"`
	IsPublished     bool             `json:"is_published"`
	IsFeatured      bool             `json:"is_featured"`
	ExternalUrl     string           `json:"external_url"`
	Category        []string         `json:"category"`
	PublishedAt     pgtype.Timestamp `json:"published_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}
