// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "https://github.com/LYK-INC/blog-backend-go"
        },
        "license": {
            "name": "MIT License"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "returns server time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get Health check status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HelloResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        },
        "/blog/related/{blog_id}": {
            "get": {
                "description": "returns Realted Blog Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blog"
                ],
                "summary": "Get Related Blog By Slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blog Id",
                        "name": "blog_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "int valid",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer",
                        "description": "int valid",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/blog.RealtedBLogsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        },
        "/blog/{blog_slug}": {
            "get": {
                "description": "returns Blog Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blog"
                ],
                "summary": "Get Blog By Slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Blog Slug",
                        "name": "blog_slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/blog.GetBlogBySlugResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        },
        "/home/articles": {
            "get": {
                "description": "returns array of articles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homepage"
                ],
                "summary": "Get homepage articles",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "int valid",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer",
                        "description": "int valid",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/homepage.ArticlesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        },
        "/home/featured": {
            "get": {
                "description": "returns featured article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homepage"
                ],
                "summary": "Get featured article",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/homepage.FeaturedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        },
        "/home/press": {
            "get": {
                "description": "returns array of articles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Homepage"
                ],
                "summary": "Get types.Press articles",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "int valid",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer",
                        "description": "int valid",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/homepage.PressResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.ErrResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "blog.GetBlogBySlugResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.BlogWithContent"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "blog.RealtedBLogsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.RealtedBlog"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "health.HelloResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "homepage.ArticlesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Blog"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "homepage.FeaturedResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Blog"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "homepage.PressResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Press"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "types.Blog": {
            "type": "object",
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "author_profile_url": {
                    "type": "string"
                },
                "blog_created_at": {
                    "type": "string"
                },
                "blog_id": {
                    "type": "integer"
                },
                "blog_thumbnail_url": {
                    "type": "string"
                },
                "category": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "read_time": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.BlogWithContent": {
            "type": "object",
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "author_profile_url": {
                    "type": "string"
                },
                "blog_created_at": {
                    "type": "string"
                },
                "blog_id": {
                    "type": "integer"
                },
                "blog_thumbnail_url": {
                    "type": "string"
                },
                "category": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "read_time": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.ErrResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "types.Press": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "external_url": {
                    "type": "string"
                },
                "press_id": {
                    "type": "integer"
                },
                "press_published_at": {
                    "type": "string"
                },
                "press_thumbnail_url": {
                    "type": "string"
                },
                "publisher_name": {
                    "type": "string"
                },
                "publisher_profile_img_link": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.RealtedBlog": {
            "type": "object",
            "properties": {
                "author_name": {
                    "type": "string"
                },
                "author_profile_url": {
                    "type": "string"
                },
                "blog_created_at": {
                    "type": "string"
                },
                "blog_id": {
                    "type": "integer"
                },
                "blog_thumbnail_url": {
                    "type": "string"
                },
                "category": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "blogapi.lykstage.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "blog server api",
	Description:      "This is a backend api server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
