name: docker deploy main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: build and push docker image
        run: |
          docker login --username tetrex --password ${{ secrets.GH_PKGS_TOKEN }} ghcr.io
          docker build -f ./docker/server/prod.dockerfile . \
          docker push ghcr.io/lyk-inc/lyk-blog-backend-go-main:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: pull latest docker image and start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/blog-backend-go
            git pull
            git checkout main
            docker login --username tetrex --password ${{ secrets.GH_PKGS_TOKEN }} ghcr.io
            docker compose -f ./docker/server/docker-compose-prod.yml pull
            docker compose -f ./docker/server/docker-compose-prod.yml up -d --remove-orphans
            docker image prune -f
